server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: service_pass
  data:
    jdbc:
      dialect: mysql
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
